import type { Simulation } from '@/types'

function levelLabel(level?: 'Low' | 'Medium' | 'High') {
  if (!level) return '—'
  return level
}

export function buildMarkdownReport(sim: Simulation): string {
  const date = new Date(sim.createdAt).toLocaleString()
  const mode = sim.mode.charAt(0).toUpperCase() + sim.mode.slice(1)
  const lines: string[] = []

  lines.push(`# SwarmMind Studio — ${mode} Report`)
  lines.push(`**Simulation:** ${sim.name}`)
  lines.push(`**Date:** ${date}`)
  lines.push(`**Agents:** ${sim.agents.map((a) => `${a.emoji} ${a.name}`).join(', ')}`)
  lines.push(`**Rounds:** ${sim.rounds}`)
  lines.push('')

  // Brief / Scenario
  lines.push('## Brief')
  lines.push('```')
  lines.push(sim.scenario.slice(0, 600) + (sim.scenario.length > 600 ? '\n[...]' : ''))
  lines.push('```')
  lines.push('')

  // Metrics
  if (sim.metrics) {
    const m = sim.metrics
    lines.push('## Metrics')
    lines.push(`| Metric | Value |`)
    lines.push(`|---|---|`)
    lines.push(`| Overall Sentiment | ${m.overallSentiment > 0.2 ? '🟢 Positive' : m.overallSentiment < -0.2 ? '🔴 Negative' : '🟡 Mixed'} (${m.overallSentiment.toFixed(2)}) |`)
    lines.push(`| Consensus Level | ${m.consensusLevel}% |`)
    lines.push(`| Positive Agents | ${m.positiveCount} / ${sim.messages.filter((m) => !m.isStreaming).length} |`)
    lines.push(`| Critical Agents | ${m.negativeCount} / ${sim.messages.filter((m) => !m.isStreaming).length} |`)

    if (sim.mode === 'consulting') {
      if (m.riskLevel) lines.push(`| Risk Level | ${levelLabel(m.riskLevel)} |`)
      if (m.implementationComplexity) lines.push(`| Complexity | ${levelLabel(m.implementationComplexity)} |`)
      if (m.decisionScore !== undefined) lines.push(`| Decision Confidence | ${m.decisionScore}/100 |`)
    }
    if (sim.mode === 'social') {
      if (m.viralityScore !== undefined) lines.push(`| Virality Score | ${m.viralityScore}/100 |`)
      if (m.controversyIndex !== undefined) lines.push(`| Controversy Index | ${m.controversyIndex}/100 |`)
      if (m.platformFit) lines.push(`| Platform Fit | ${levelLabel(m.platformFit)} |`)
    }
    if (sim.mode === 'research') {
      if (m.evidenceStrength !== undefined) lines.push(`| Evidence Strength | ${m.evidenceStrength}/100 |`)
      if (m.practicalApplicability) lines.push(`| Practical Applicability | ${levelLabel(m.practicalApplicability)} |`)
      if (m.researchGapScore !== undefined) lines.push(`| Research Gap | ${m.researchGapScore}/100 |`)
    }
    if (sim.mode === 'fashion') {
      if (m.trendScore !== undefined) lines.push(`| Trend Score | ${m.trendScore}/100 |`)
      if (m.sellThroughPrediction !== undefined) lines.push(`| Sell-Through Est. | ~${m.sellThroughPrediction}% |`)
      if (m.licensingFitScore !== undefined) lines.push(`| Licensing Fit | ${m.licensingFitScore}/100 |`)
      if (m.viralityPotential) lines.push(`| Virality Potential | ${m.viralityPotential} |`)
      if (m.sustainabilityRisk) lines.push(`| ESG Risk | ${m.sustainabilityRisk} |`)
    }
    lines.push('')

    lines.push('## Key Insights')
    m.keyInsights.forEach((i) => lines.push(`- ${i}`))
    lines.push('')
  }

  // Agent scores
  const scored = sim.messages.filter((m) => m.score)
  if (scored.length > 0) {
    lines.push('## Agent Verdicts (Final Round)')
    scored.forEach((m) => {
      lines.push(`### ${m.agentEmoji} ${m.agentName} — Score ${m.score!.value}/10 (${m.score!.confidence} confidence)`)
      lines.push(`> ${m.score!.keyPoint}`)
      lines.push('')
    })
  }

  // Full debate
  lines.push('## Full Debate Transcript')
  let currentRound = 0
  sim.messages.forEach((msg) => {
    if (msg.round !== currentRound) {
      currentRound = msg.round
      const roundLabel = currentRound === 1 ? 'Opening Positions' : currentRound === 2 ? 'Cross-Examination' : 'Final Verdicts'
      lines.push(`\n### Round ${currentRound} — ${roundLabel}\n`)
    }
    lines.push(`**${msg.agentEmoji} ${msg.agentName}** *(${msg.agentRole})*`)
    lines.push(msg.content)
    lines.push('')
  })

  lines.push('---')
  lines.push('*Generated by SwarmMind Studio*')

  return lines.join('\n')
}

export function copyReport(sim: Simulation) {
  const md = buildMarkdownReport(sim)
  navigator.clipboard.writeText(md)
}

export function downloadReport(sim: Simulation) {
  const md = buildMarkdownReport(sim)
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `swarmmind-${sim.name.toLowerCase().replace(/\s+/g, '-').slice(0, 40)}.md`
  a.click()
  URL.revokeObjectURL(url)
}
